In [5]:
import numpy as np
import matplotlib.pyplot as py
def rref_matrix(A):
    l = []
    m, n = np.shape(A)
    i = 0
    j = 0
    rank = 0
    while i <= m - 1 and j <= n - 1:
        p = np.max(np.abs(A[i:m, j]))
        max_p = np.argmax(np.abs(A[i:m, j]))
        k = max_p + i
        if p == 0 or p <= 1e-10:
            j = j + 1
        else:
            rank = rank + 1
            C = A.copy()
            C[k, :] = A[i, :]
            C[i, :] = A[k, :]
            A = C.copy()
            A[i, :] = A[i, :] / A[i, j]
            l.append(j)
            for x in range(0, m):
                if x != i:
                    A[x, :] = A[x, :] - A[x, j] * A[i, :]
            i = i + 1
            j = j + 1
    return A, rank, l

def null_space(rref):
    pivots = []
    for row in rref:
        for j,val in enumerate(row):
            if val == 1:
                pivots.append(j)
                break

    n_cols = len(rref[0])
    null_basis = []

    for j in range(n_cols):
        if j not in pivots:
            vec = np.zeros(n_cols)
            vec[j] = 1
            for i in range(len(pivots)):
                pivot_col = pivots[i]
                vec[pivot_col] = -rref[i, j]
            null_basis.append(vec)

    print("Null Space Basis:")
    for basis_vec in null_basis:
        print(basis_vec)

P1=7/20
P2=11/50
P3=457/1000
P1f=389/1000
P2f=151/611
P3f=7/10
M12=4/25
M23=37/100
M12f=23/100
M23f=2/5
F2m=1
F2f=2
L=([P1,0,0,0,F2m,0],
   [M12,P2,0,0,0,0],
   [0,M23,P3,0,0,0],
   [0,0,0,P1f,F2f,0],
   [0,0,0,M12f,P2f,0],
   [0,0,0,0,M23f,P3f])

I=np.eye(6,dtype=int)

new_matrix = L - I

print(new_matrix)

RREF, rank, leading_columns = rref_matrix(new_matrix)
print("rref is - \n", RREF)

print("Basis of Null space of the matrix --->")
null_space(RREF)

[[-0.65        0.          0.          0.          1.          0.        ]
 [ 0.16       -0.78        0.          0.          0.          0.        ]
 [ 0.          0.37       -0.543       0.          0.          0.        ]
 [ 0.          0.          0.         -0.611       2.          0.        ]
 [ 0.          0.          0.          0.23       -0.75286416  0.        ]
 [ 0.          0.          0.          0.          0.4        -0.3       ]]
rref is - 
 [[ 1.          0.          0.          0.          0.         -1.15384615]
 [ 0.          1.          0.          0.          0.         -0.23668639]
 [ 0.          0.          1.          0.          0.         -0.16127802]
 [ 0.          0.          0.          1.          0.         -2.45499182]
 [ 0.          0.          0.          0.          1.         -0.75      ]
 [ 0.          0.          0.          0.          0.          0.        ]]
Basis of Null space of the matrix --->
Null Space Basis:
[1.15384615 0.23668639 0.1612

array(None, dtype=object)